# container copy
POST https://localhost:7179/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "targetcs",
  "blobName": "test2/auth4.gif",
  "sourceContainer": "testdir",
  "targetContainer": "01k",
  "requestType": "c"
}

### test background
POST https://localhost:7179/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "targetcs",
  "blobName": "test2/auth4.gif",
  "sourceContainer": "1000files",
  "targetContainer": "test1000",
  "requestType": "c"
}

###
# single blob copy
POST https://localhost:7179/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "targetcs",
  "blobName": "test2/auth4.gif",
  "sourceContainer": "testdir",
  "targetContainer": "01k",
  "requestType": "b"
}

###
# create sample
POST https://second--21ksnzn.jollyrock-6da7e977.northeurope.azurecontainerapps.io/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "targetcs",
  "blobName": "https://raw.githubusercontent.com/soferreira/copy-alternatives/main/sample_data/daily.data",
  "sourceContainer": "testdir",
  "targetContainer": "5stream",
  "requestType": "s",
  "sampleSize": 500
}


### local

POST https://localhost:7179/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "sourcecs",
  "blobName": "https://raw.githubusercontent.com/soferreira/copy-alternatives/main/sample_data/daily.data",
  "sourceContainer": "testdir",
  "targetContainer": "501500",
  "requestType": "s",
  "SampleSize": 500,
  "CallonUrl": "https://localhost:7179"
}

### test aca

POST https://second--s2cz39w.jollyrock-6da7e977.northeurope.azurecontainerapps.io/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "sourcecs",
  "blobName": "https://raw.githubusercontent.com/soferreira/copy-alternatives/main/sample_data/daily.data",
  "sourceContainer": "testdir",
  "targetContainer": "10files",
  "requestType": "s",
  "sampleSize": 10000
}

###

POST https://second--s2cz39w.jollyrock-6da7e977.northeurope.azurecontainerapps.io/api/Blob
accept: text/plain
Content-Type: application/json

{
  "sourceCS": "sourcecs",
  "targetCS": "targetcs",
  "blobName": "test2/auth4.gif",
  "sourceContainer": "5000files",
  "targetContainer": "aca5000",
  "requestType": "c"
}

###

POST https://second--s2cz39w.jollyrock-6da7e977.northeurope.azurecontainerapps.io/api/Blob
accept: text/plain
Content-Type: application/json